services:
  backend:
    build: ../kamppis-server
    container_name: kamppis-server
    ports:
      - "8080:8080"
    volumes:
      - ../kamppis-server/src:/app/src
      - ../kamppis-server/build:/app/build
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    command: ["./gradlew", "bootRun"]

  frontend:
    build: ../kamppis-app
    container_name: kamppis-app
    depends_on:
      - backend
    ports:
      - "8081:8081"
      - "19000:19000"
      - "19001:19001"
      - "19002:19002"
    volumes:
      - ../kamppis-app:/app
      - /app/node_modules # Avoid overwriting node_modules
    environment:
      - BACKEND_URL=http://backend:8080
    command: ["npm", "start", "--", "--tunnel"]

