networks:
  kamppis-network:
    driver: bridge

services:
  backend:
    build: ../kamppis-server
    container_name: kamppis-backend
    networks:
      - kamppis-network
    ports:
      - "8080:8080"
    volumes:
      - ../kamppis-server/src:/app/src
      - ../kamppis-server/target:/app/target
    environment:
      - SPRING_DEVTOOLS_RESTART_ENABLED=true

  frontend:
    build: ../kamppis-app
    container_name: kamppis-frontend
    networks:
      - kamppis-network
    ports:
      - "8081:8081"
      - "19000:19000"
      - "19001:19001"
      - "19002:19002"
      - "19006:19006"
    volumes:
      - ../kamppis-app:/app
      - /app/node_modules # Avoid overwriting node_modules
    environment:
      - BACKEND_URL=http://backend:8080
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
    stdin_open: true
    tty: true
