version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    volumes:
      - ./backend/src:/app/src
      - ./backend/target:/app/target
    environment:
      - SPRING_DEVTOOLS_RESTART_ENABLED=true

  frontend:
    build: ./frontend
    ports:
      - "8081:8081"
      - "19000:19000"
      - "19001:19001"
      - "19002:19002"
      - "19006:19006"
    volumes:
      - ./frontend:/app
      - /app/node_modules # Avoid overwriting node_modules
    environment:
      - BACKEND_URL=http://backend:8080
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
    stdin_open: true
    tty: true
