networks:
  kamppis-network:
    driver: bridge

services:
  backend:
    build: ../kamppis-server
    container_name: kamppis-backend
    networks:
      - kamppis-network
    ports:
      - "8080:8080"
    volumes:
      - ../kamppis-server/src:/app/src
      - ../kamppis-server/target:/app/target
    environment:
      - SPRING_DEVTOOLS_RESTART_ENABLED=true

  frontend:
    build: ../kamppis-app
    container_name: kamppis-frontend
    networks:
      - kamppis-network
    ports:
      - "8081:8081" # Metro Bundler
      - "19000:19000" # Expo DevTools
      - "19001:19001" # LAN Debugging
      - "19002:19002" # Tunnel Debugging
      - "19006:19006" # Expo Web (optional)
    volumes:
      - ../kamppis-app:/app
      - /app/node_modules # Avoid overwriting node_modules
    environment:
      - BACKEND_URL=http://host.docker.internal:8080
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
      - CHOKIDAR_USEPOLLING=true # Fix for file watching inside Docker
      - WATCHPACK_POLLING=true # Alternative fix for watching files
    stdin_open: true
    tty: true
