export enum Utilities {
  WIFI = "WIFI",
  DISHWASHER = "DISHWASHER",
  LAUNDRY_MACHINE = "LAUNDRY_MACHINE",
  BALCONY = "BALCONY",
  PRIVATE_BATHROOM = "PRIVATE_BATHROOM",
  SEPARATE_BATHROOM_AND_SHOWER = "SEPARATE_BATHROOM_AND_SHOWER",
  // Additional utilities - these are not in the backend yet
  //AIR_CONDITIONING = "AIR_CONDITIONING",
  //FURNISHED = "FURNISHED",
  //PARKING = "PARKING",
  //GYM = "GYM",
  //POOL = "POOL",
  //PET_FRIENDLY = "PET_FRIENDLY",
  //SMOKING_ALLOWED = "SMOKING_ALLOWED",
}
